#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    exit("Run from CLI only!\n");
}

require_once 'vendor/autoload.php';
require_once 'config/bootstrap.php';
require_once  'app/CoreClasses/Mini/mini.php';




$method_name=$argv[2];

if(!empty($argv[3])){
    echo  (new $class_name())->$method_name($argv[3]);
    return;
}

(new $class_name())->$method_name();

